/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        //IMPORTAR EL PANEL
        //inicio_gestion  = new inicio_gestion();
        ig.setSize(800, 500);
        ig.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(ig, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }

    inicio_gestion ig = new inicio_gestion(); //importar panel inicio gestion

    fondo_panel fondo = new fondo_panel();
    
    eventoCerrar eventoCerrar = new eventoCerrar();
    
    

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/Gestion1.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
     class eventoCerrar implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent arg0) {
            // TODO Auto-generated method stub
            dispose();
        }
    }
    //iconos
    ImageIcon ichorarios = new ImageIcon("src/main/java/Iconos/reloj1.png");
    ImageIcon icalumno = new ImageIcon("src/main/java/Iconos/Gestion2.png");
    ImageIcon prueba = new ImageIcon("src/main/java/Iconos/gestion-de-equipos.png");
    ImageIcon inicio = new ImageIcon("src/main/java/Iconos/hogar.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new fondo_panel();
        contenedor = new javax.swing.JPanel();
        customButtons3 = new EVD1.CustomButtons();
        customButtons2 = new EVD1.CustomButtons();
        customButtons1 = new EVD1.CustomButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(850, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel3.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 800, 500));

        customButtons3.setIcon(icalumno);
        customButtons3.setName(""); // NOI18N
        customButtons3.setRippleColor(new java.awt.Color(51, 51, 51));
        customButtons3.setSelected(true);
        customButtons3.setShadowColor(new java.awt.Color(255, 255, 255));
        customButtons3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtons3ActionPerformed(evt);
            }
        });
        jPanel3.add(customButtons3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 50));

        customButtons2.setIcon(ichorarios);
        customButtons2.setRippleColor(new java.awt.Color(51, 51, 51));
        customButtons2.setShadowColor(new java.awt.Color(255, 255, 255));
        customButtons2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtons2ActionPerformed(evt);
            }
        });
        jPanel3.add(customButtons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        customButtons1.setIcon(inicio);
        customButtons1.setRippleColor(new java.awt.Color(51, 51, 51));
        customButtons1.setShadowColor(new java.awt.Color(255, 255, 255));
        customButtons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtons1ActionPerformed(evt);
            }
        });
        jPanel3.add(customButtons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customButtons3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtons3ActionPerformed
        // TODO add your handling code here:
        Gestion_usuarios gu = new Gestion_usuarios();
        gu.setSize(800, 500);
        gu.setLocation(0, 0);

        contenedor.removeAll();;
        contenedor.add(gu, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_customButtons3ActionPerformed

    private void customButtons2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtons2ActionPerformed
        Gestion_horarios gh = new Gestion_horarios();
        gh.setSize(800, 500);
        gh.setLocation(0, 0);

        contenedor.removeAll();;
        contenedor.add(gh, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_customButtons2ActionPerformed

    private void customButtons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtons1ActionPerformed
        // TODO add your handling code here:
        ig.setSize(800, 500);
        ig.setLocation(0, 0);

        contenedor.removeAll();;
        contenedor.add(ig, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_customButtons1ActionPerformed

    private void listener(java.awt.event.ActionEvent evt)
    {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private EVD1.CustomButtons customButtons1;
    private EVD1.CustomButtons customButtons2;
    private EVD1.CustomButtons customButtons3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
