/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class Lab_windows extends javax.swing.JFrame {

    /**
     * Creates new form Login_alumno
     */
    public Lab_windows() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/Pantalla_inicio_(1).png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

    login_admin lgadmin = new login_admin();
    foraneo foraneo = new foraneo();
    ImageIcon iconobtn3 = new ImageIcon("src/main/java/Iconos/llave.png");
    ImageIcon iconobtn4 = new ImageIcon("src/main/java/Iconos/llave2.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new fondo_panel();
        login_admin = new EVD1.CustomButtons();
        btn_escanerforaneo = new EVD1.CustomButtons();
        btn_foraneo1 = new EVD1.CustomButtons();
        btn_alumno = new EVD1.CustomButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_admin.setIcon( iconobtn3);
        login_admin.setBackground(new java.awt.Color(29, 53, 100));
        login_admin.setIcon(iconobtn3);
        login_admin.setRippleColor(new java.awt.Color(255, 255, 255));
        login_admin.setShadowColor(new java.awt.Color(255, 255, 255));
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_adminActionPerformed(evt);
            }
        });

        login_admin.setIcon( iconobtn3);
        btn_escanerforaneo.setBackground(new java.awt.Color(29, 53, 100));
        btn_escanerforaneo.setForeground(new java.awt.Color(255, 255, 255));
        btn_escanerforaneo.setText("ESCANEA AQUÍ");
        btn_escanerforaneo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_escanerforaneo.setRippleColor(new java.awt.Color(255, 255, 255));
        btn_escanerforaneo.setShadowColor(new java.awt.Color(255, 255, 255));
        btn_escanerforaneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escanerforaneoActionPerformed(evt);
            }
        });

        login_admin.setIcon( iconobtn3);
        btn_foraneo1.setBackground(new java.awt.Color(29, 53, 100));
        btn_foraneo1.setForeground(new java.awt.Color(255, 255, 255));
        btn_foraneo1.setText("RELLENA TU FORMULARIO AQUÍ");
        btn_foraneo1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_foraneo1.setRippleColor(new java.awt.Color(255, 255, 255));
        btn_foraneo1.setShadowColor(new java.awt.Color(255, 255, 255));
        btn_foraneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_foraneo1ActionPerformed(evt);
            }
        });

        login_admin.setIcon( iconobtn3);
        btn_alumno.setForeground(new java.awt.Color(0, 0, 0));
        btn_alumno.setText("ESCANEA TU CODIGO");
        btn_alumno.setActionCommand("ESCANEA TU CÓDIGO");
        btn_alumno.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        btn_alumno.setRippleColor(new java.awt.Color(0, 0, 0));
        btn_alumno.setShadowColor(new java.awt.Color(0, 0, 0));
        btn_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(780, 780, 780)
                        .addComponent(login_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_foraneo1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_escanerforaneo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_foraneo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(btn_escanerforaneo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(login_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_adminActionPerformed
        Seleccionar_laboratorio sl = new Seleccionar_laboratorio();
        lgadmin.setVisible(true);
        this.dispose();
        lgadmin.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                sl.setVisible(true);
            }
        }); 
    }//GEN-LAST:event_login_adminActionPerformed

    private void btn_escanerforaneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escanerforaneoActionPerformed
Escanear_Foraneo_w escan_f = new Escanear_Foraneo_w();
        if (evt.getSource() == btn_escanerforaneo) {
            btn_alumno.setEnabled(false);
            btn_foraneo1.setEnabled(false);
            btn_escanerforaneo.setEnabled(false);
            login_admin.setEnabled(false);

            escan_f.setVisible(true);

            escan_f.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                }

                public void windowClosed(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                }
            });
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_escanerforaneoActionPerformed

    private void btn_foraneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_foraneo1ActionPerformed
 this.dispose();
        foraneo.setVisible(true);
        foraneo.addWindowListener(new WindowAdapter(){
            @Override
                public void windowClosing(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                    setVisible(true);
                }

                public void windowClosed(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                    setVisible(true);
                }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_btn_foraneo1ActionPerformed

    private void btn_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnoActionPerformed
        
        Escaner_alumno_w escaum = new Escaner_alumno_w();
        if (evt.getSource() == btn_alumno) {
            btn_alumno.setEnabled(false);
            btn_foraneo1.setEnabled(false);
            btn_escanerforaneo.setEnabled(false);
            login_admin.setEnabled(false);

            escaum.setVisible(true);

            escaum.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                }

                public void windowClosed(WindowEvent we) {
                    btn_alumno.setEnabled(true);
                    btn_foraneo1.setEnabled(true);
                    btn_escanerforaneo.setEnabled(true);
                    login_admin.setEnabled(true);
                }
            });
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_alumnoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EVD1.CustomButtons btn_alumno;
    private EVD1.CustomButtons btn_escanerforaneo;
    private EVD1.CustomButtons btn_foraneo1;
    private javax.swing.JPanel jPanel2;
    private EVD1.CustomButtons login_admin;
    // End of variables declaration//GEN-END:variables
}
