/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Metodos.Setters_getters;
import coneccion.Conection;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class login_admin extends javax.swing.JFrame {

    /**
     * Creates new form login_admin
     */
    public login_admin() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/Pantalla_inicio.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    Conection con = new Conection();
    Gestion ges = new Gestion();
//    Seleccionar_laboratorio seleclab = new Seleccionar_laboratorio();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new fondo_panel();
        txt_usuario = new javax.swing.JTextField();
        txt_contra = new javax.swing.JPasswordField();
        btn_regreso = new EVD1.CustomButtons();
        btn_ingreso1 = new EVD1.CustomButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 270, 40));
        jPanel2.add(txt_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 270, 40));

        btn_regreso.setBackground(new java.awt.Color(51, 51, 51));
        btn_regreso.setForeground(new java.awt.Color(255, 255, 255));
        btn_regreso.setText("REGRESO");
        btn_regreso.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_regreso.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_regreso.setShadowColor(new java.awt.Color(0, 0, 0));
        btn_regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 130, 50));

        btn_ingreso1.setBackground(new java.awt.Color(51, 51, 51));
        btn_ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingreso1.setText("INGRESAR");
        btn_ingreso1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_ingreso1.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_ingreso1.setShadowColor(new java.awt.Color(153, 153, 153));
        btn_ingreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingreso1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingreso1ActionPerformed
String usuario_admin = txt_usuario.getText();
        String contrasena_admin = String.valueOf(txt_contra.getPassword());

        Setters_getters.setContra(contrasena_admin);
        Setters_getters.setUsuario(usuario_admin);

        con.conectar();
        if (con.ban == true) {
            ges.setVisible(true);
            this.dispose();
            txt_contra.setText("");
            ges.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    setVisible(true);
                }

                @Override
                public void windowClosed(WindowEvent we) {
                    setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_btn_ingreso1ActionPerformed

    private void btn_regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresoActionPerformed
        Seleccionar_laboratorio seleclab = new Seleccionar_laboratorio();
        this.dispose();
        seleclab.setVisible(true);
    }//GEN-LAST:event_btn_regresoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EVD1.CustomButtons btn_ingreso1;
    private EVD1.CustomButtons btn_regreso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_contra;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
