/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Funciones.Eliminar;
import Funciones.Modificar;
import Funciones.Guardar;
import Funciones.Seleccionar;
import coneccion.Conection;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import java.awt.event.WindowAdapter;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emili
 */
public class profesores extends javax.swing.JPanel {

    private Component rootPane;

    /**
     * Creates new form profesores
     */
    public profesores() {
        initComponents();
        c = new Conection().conectar();
        select = new Seleccionar(c);
        limpiar_profesorelim();
        limpiar_profesormod();
        limpiar_profesorselec();
    }

    Guardar guardar;
    Connection c;
    Seleccionar select;
    Eliminar elim = new Eliminar();
    Modificar mod = new Modificar();
    int contador = 0;

    public void limpiar_profesoreguardar() {
        txt_nom.setText("");
        txt_pat.setText("");
        txt_mat.setText("");
        txt_plaza.setText("");
    }

    public void limpiar_profesorelim() {
        combo_eliminar.removeAllItems();
        combo_eliminar.addItem("Seleccione una plaza");
        c = new Conection().conectar();
        String[] barras = select.numplaza_profesor();

        for (String i : barras) {
            combo_eliminar.addItem(i);
            contador++;
        }
        txt_nomp.setText("");
        txt_patp.setText("");
        txt_matp.setText("");
    }

    public void limpiar_profesormod() {
        combo_modificar.removeAllItems();
        combo_modificar.addItem("Seleccione una plaza");
        c = new Conection().conectar();
        String[] barras = select.numplaza_profesor();

        for (String i : barras) {
            combo_modificar.addItem(i);
            contador++;
        }

        txt_nomm.setText("");
        txt_patm.setText("");
        txt_matm.setText("");
    }

    public void limpiar_profesorselec() {
        combo_seleccionar.removeAllItems();
        combo_seleccionar.addItem("Seleccione una plaza");
        c = new Conection().conectar();
        String[] barras = select.numplaza_profesor();

        for (String i : barras) {
            combo_seleccionar.addItem(i);
            contador++;
        }
        txt_noms.setText("");
        txt_pats.setText("");
        txt_mats.setText("");
    }

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/opciones.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    fondo2 fondosec = new fondo2();

    class fondo2 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/tablas.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    public void limpiar_eliminar() {
        combo_eliminar.removeAllItems();
        combo_eliminar.addItem("Seleccione");

        txt_nomp.setText("");
        txt_patp.setText("");
        txt_matp.setText("");
    }

    Guardar g = new Guardar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo_panel();
        materialTabbed1 = new EVD1.MaterialTabbed();
        jPanel2 = new fondo2();
        txt_nom = new EVD1.TextField();
        txt_pat = new EVD1.TextField();
        txt_mat = new EVD1.TextField();
        txt_plaza = new EVD1.TextField();
        btn_guardar = new EVD1.CustomButtons();
        jPanel3 = new fondo2();
        combo_modificar = new EVD2.Combobox();
        txt_nomm = new EVD1.TextField();
        txt_patm = new EVD1.TextField();
        txt_matm = new EVD1.TextField();
        btn_profesores_mod = new EVD1.CustomButtons();
        jPanel4 = new fondo2();
        txt_nomp = new EVD1.TextField();
        txt_patp = new EVD1.TextField();
        txt_matp = new EVD1.TextField();
        combo_eliminar = new EVD2.Combobox();
        btn_profesores_el = new EVD1.CustomButtons();
        jPanel5 = new fondo2();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_profesores = new javax.swing.JTable();
        btn_seleccionar = new EVD1.CustomButtons();
        combo_seleccionar = new EVD2.Combobox();
        txt_noms = new EVD1.TextField();
        txt_pats = new EVD1.TextField();
        txt_mats = new EVD1.TextField();

        materialTabbed1.setBackground(new java.awt.Color(255, 255, 255));
        materialTabbed1.setForeground(new java.awt.Color(255, 255, 255));
        materialTabbed1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N

        txt_nom.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_nom.setLabelText("NOMBRE");
        txt_nom.setName(""); // NOI18N

        txt_pat.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_pat.setLabelText("APELLIDO PATERNO");
        txt_pat.setName(""); // NOI18N

        txt_mat.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_mat.setLabelText("APELLIDO PATERNO");
        txt_mat.setName(""); // NOI18N

        txt_plaza.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_plaza.setLabelText("NUMERO DE PLAZA");
        txt_plaza.setName(""); // NOI18N

        btn_guardar.setBackground(new java.awt.Color(51, 51, 51));
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("GUARDAR");
        btn_guardar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_guardar.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_guardar.setSelected(true);
        btn_guardar.setShadowColor(new java.awt.Color(204, 204, 204));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_plaza, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_plaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("GUARDAR", jPanel2);

        combo_modificar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        combo_modificar.setLabeText("");
        combo_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_modificarActionPerformed(evt);
            }
        });

        txt_nomm.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_nomm.setLabelText("NOMBRE");
        txt_nomm.setName(""); // NOI18N

        txt_patm.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_patm.setLabelText("APELLIDO PATERNO");
        txt_patm.setName(""); // NOI18N

        txt_matm.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_matm.setLabelText("APELLIDO MATERNO");
        txt_matm.setName(""); // NOI18N

        btn_profesores_mod.setBackground(new java.awt.Color(51, 51, 51));
        btn_profesores_mod.setForeground(new java.awt.Color(255, 255, 255));
        btn_profesores_mod.setText("MODIFICAR");
        btn_profesores_mod.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_profesores_mod.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_profesores_mod.setSelected(true);
        btn_profesores_mod.setShadowColor(new java.awt.Color(204, 204, 204));
        btn_profesores_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profesores_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_profesores_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_patm, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_matm, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_nomm, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(87, 140, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(combo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(combo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nomm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_patm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_profesores_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("MODIFICAR", jPanel3);

        txt_nomp.setEditable(false);
        txt_nomp.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_nomp.setLabelText("NOMBRE");
        txt_nomp.setName(""); // NOI18N

        txt_patp.setEditable(false);
        txt_patp.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_patp.setLabelText("APELLIDO PATERNO");
        txt_patp.setName(""); // NOI18N

        txt_matp.setEditable(false);
        txt_matp.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_matp.setLabelText("APELLIDO MATERNO");
        txt_matp.setName(""); // NOI18N
        txt_matp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matpActionPerformed(evt);
            }
        });

        combo_eliminar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        combo_eliminar.setLabeText("");
        combo_eliminar.setLightWeightPopupEnabled(false);
        combo_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_eliminarActionPerformed(evt);
            }
        });

        btn_profesores_el.setBackground(new java.awt.Color(51, 51, 51));
        btn_profesores_el.setForeground(new java.awt.Color(255, 255, 255));
        btn_profesores_el.setText("ELIMINAR");
        btn_profesores_el.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_profesores_el.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_profesores_el.setSelected(true);
        btn_profesores_el.setShadowColor(new java.awt.Color(204, 204, 204));
        btn_profesores_el.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profesores_elActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_profesores_el, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txt_patp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_matp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_nomp, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(combo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_patp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_profesores_el, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("ELIMINAR", jPanel4);

        tabla_profesores.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        tabla_profesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "NÚMERO DE PLAZA"
            }
        ));
        jScrollPane1.setViewportView(tabla_profesores);

        btn_seleccionar.setBackground(new java.awt.Color(51, 51, 51));
        btn_seleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btn_seleccionar.setText("SELECCIONAR");
        btn_seleccionar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btn_seleccionar.setRippleColor(new java.awt.Color(204, 204, 204));
        btn_seleccionar.setShadowColor(new java.awt.Color(153, 153, 153));
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        combo_seleccionar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        combo_seleccionar.setLabeText("");
        combo_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_seleccionarActionPerformed(evt);
            }
        });

        txt_noms.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_noms.setLabelText("NOMBRE");
        txt_noms.setName(""); // NOI18N

        txt_pats.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_pats.setLabelText("APELLIDO PATERNO");
        txt_pats.setName(""); // NOI18N

        txt_mats.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        txt_mats.setLabelText("APELLIDO PATERNO");
        txt_mats.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_pats, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mats, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txt_noms, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(combo_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(combo_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_noms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("SELECCIONAR", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_matpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matpActionPerformed

    private void combo_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_eliminarActionPerformed
        try {
            String plaza = combo_eliminar.getSelectedItem().toString();
            if (plaza.equals("Seleccione una plaza")) {
                //c = new Conecction().conectar();
                txt_nomp.setText("");
                txt_patp.setText("");
                txt_matp.setText("");
            } else {
                c = new Conection().conectar();
                String datos[] = select.profesor_plazabusq(plaza);
                txt_nomp.setText(datos[0]);
                txt_patp.setText(datos[1]);
                txt_matp.setText(datos[2]);
            }
        } catch (Exception x) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_combo_eliminarActionPerformed

    private void btn_profesores_elActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profesores_elActionPerformed
        String numero_plaza = combo_eliminar.getSelectedItem().toString();

        int d = JOptionPane.showConfirmDialog(null, " ¡¿Seguro que desea eliminar este registro?!", "Cita", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (d == JOptionPane.YES_OPTION) {
            //elim.eliminar_profesor(rfcc);
            elim.eliminar_profesor(numero_plaza);
            txt_nom.setText("");
            txt_patp.setText("");
            txt_matp.setText("");
            limpiar_eliminar();
        } else {
            JOptionPane.showMessageDialog(null, "No se Elimino nada!!", "mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_profesores_elActionPerformed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        try {
            DefaultTableModel modelado = new DefaultTableModel();
            tabla_profesores.setModel(modelado);

            //Agregar tres variables
            PreparedStatement ps = null;
            ResultSet rs = null;
            //Connection con= getConection();
            c = new Conection().conectar();
            String sql = "SELECT nombre_p, ap_pat, ap_mat, num_plaza FROM profesores order by id_profesor ASC;";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMetaD = rs.getMetaData();
            int cant_columnas = rsMetaD.getColumnCount();

            modelado.addColumn("NOMBRE");
            modelado.addColumn("APELLIDO PATERNO");
            modelado.addColumn("APELLIDO MATERNO");
            modelado.addColumn("NÚMERO DE PLAZA");

            while (rs.next()) {
                Object[] filas = new Object[cant_columnas];

                for (int i = 0; i < cant_columnas; i++) {
                    filas[i] = rs.getObject(i + 1);

                }
                modelado.addRow(filas);
            }
        } catch (Exception e) {
            System.out.println("e");
        }
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    private void combo_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_seleccionarActionPerformed
        try {
            String plaza = combo_seleccionar.getSelectedItem().toString();
            if (plaza.equals("Seleccione")) {
                //c = new Conecction().conectar();
                txt_noms.setText("");
                txt_pats.setText("");
                txt_mats.setText("");
            } else {
                c = new Conection().conectar();
                String datos[] = select.profesor_plazabusq(plaza);
                txt_noms.setText(datos[0]);
                txt_pats.setText(datos[1]);
                txt_mats.setText(datos[2]);
            }
        } catch (Exception x) {
        }
    }//GEN-LAST:event_combo_seleccionarActionPerformed

    private void combo_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_modificarActionPerformed
        try {
            String plaza = combo_modificar.getSelectedItem().toString();
            if (plaza.equals("Seleccione")) {
                //c = new Conecction().conectar();
                txt_nomm.setText("");
                txt_patm.setText("");
                txt_matm.setText("");
            } else {
                c = new Conection().conectar();
                String datos[] = select.profesor_plazabusq(plaza);
                txt_nomm.setText(datos[0]);
                txt_patm.setText(datos[1]);
                txt_matm.setText(datos[2]);
            }
        } catch (Exception x) {
        }

    }//GEN-LAST:event_combo_modificarActionPerformed

    private void btn_profesores_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profesores_modActionPerformed
        if (txt_nomm.getText().equals("") || txt_patm.getText().equals("") || txt_matm.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        } else {

            int g = JOptionPane.showConfirmDialog(null, " ¡¿Seguro que desea modificar este registro?!", "Cita", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (g == JOptionPane.YES_OPTION) {

                String nombre = txt_nomm.getText();
                String paterno = txt_patm.getText();
                String materno = txt_matm.getText();
                String plaza = combo_modificar.getSelectedItem().toString();

                mod.modificar_profesor(nombre, paterno, materno, plaza);
                limpiar_profesormod();
            } else {
                JOptionPane.showMessageDialog(null, "No se Modifico nada!!!", "mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_profesores_modActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String nombre = txt_nom.getText();
        String pat = txt_pat.getText();
        String mat = txt_mat.getText();
        String plaza = txt_plaza.getText();

        if (!plaza.equals("")) {
            g.guardar_profesores(nombre, pat, mat, plaza);
            JOptionPane.showMessageDialog(rootPane, "Registro guardado");
            limpiar_profesoreguardar();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingrese una plaza");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EVD1.CustomButtons btn_guardar;
    private EVD1.CustomButtons btn_profesores_el;
    private EVD1.CustomButtons btn_profesores_mod;
    private EVD1.CustomButtons btn_seleccionar;
    private EVD2.Combobox combo_eliminar;
    private EVD2.Combobox combo_modificar;
    private EVD2.Combobox combo_seleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private EVD1.MaterialTabbed materialTabbed1;
    private javax.swing.JTable tabla_profesores;
    private EVD1.TextField txt_mat;
    private EVD1.TextField txt_matm;
    private EVD1.TextField txt_matp;
    private EVD1.TextField txt_mats;
    private EVD1.TextField txt_nom;
    private EVD1.TextField txt_nomm;
    private EVD1.TextField txt_nomp;
    private EVD1.TextField txt_noms;
    private EVD1.TextField txt_pat;
    private EVD1.TextField txt_patm;
    private EVD1.TextField txt_patp;
    private EVD1.TextField txt_pats;
    private EVD1.TextField txt_plaza;
    // End of variables declaration//GEN-END:variables
}
