/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Emili
 */
public class Seleccionar_laboratorio extends javax.swing.JFrame {

    /**
     * Creates new form Seleccionar_laboratorio
     */
    public Seleccionar_laboratorio() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    fondo_panel fondo = new fondo_panel();

    class fondo_panel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon("src/main/java/Iconos/seleccionar_lab.png").getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }
    ImageIcon iconobtn3 = new ImageIcon("src/main/java/Iconos/llave.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo_panel();
        lab_windows = new javax.swing.JLabel();
        lab_linuxb = new javax.swing.JLabel();
        lab_linuxa1 = new javax.swing.JLabel();
        customButtons1 = new EVD1.CustomButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Seleecionar laborstorio"); // NOI18N
        setUndecorated(true);

        lab_windows.setToolTipText("WINDOWS");
        lab_windows.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_windows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_windowsMouseClicked(evt);
            }
        });

        lab_linuxb.setToolTipText("LINUX_B");
        lab_linuxb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_linuxb.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lab_linuxb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_linuxbMouseClicked(evt);
            }
        });

        lab_linuxa1.setToolTipText("LINUX_A");
        lab_linuxa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_linuxa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_linuxa1MouseClicked(evt);
            }
        });

        customButtons1.setIcon( iconobtn3);
        customButtons1.setBackground(new java.awt.Color(51, 51, 51));
        customButtons1.setRippleColor(new java.awt.Color(255, 255, 255));
        customButtons1.setShadowColor(new java.awt.Color(0, 0, 0));
        customButtons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButtons1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lab_windows, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(lab_linuxa1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(lab_linuxb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_linuxa1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_linuxb, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_windows, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(customButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lab_windowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_windowsMouseClicked
        // TODO add your handling code here:
        Lab_windows labwin = new Lab_windows();
        labwin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lab_windowsMouseClicked

    private void lab_linuxbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_linuxbMouseClicked
        // TODO add your handling code here:
        Lab_Linux_B lablib = new Lab_Linux_B();
        this.dispose();
        lablib.setVisible(true);

    }//GEN-LAST:event_lab_linuxbMouseClicked

    private void lab_linuxa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_linuxa1MouseClicked
        // TODO add your handling code here:
        Lab_Linux_A lablib = new Lab_Linux_A();
        this.dispose();
        lablib.setVisible(true);

    }//GEN-LAST:event_lab_linuxa1MouseClicked

    private void customButtons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButtons1ActionPerformed
        // TODO add your handling code here:
        login_admin logadmin = new login_admin();
        this.dispose();
        logadmin.setVisible(true);
        logadmin.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                setVisible(true);
            }

        });


    }//GEN-LAST:event_customButtons1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccionar_laboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EVD1.CustomButtons customButtons1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab_linuxa1;
    private javax.swing.JLabel lab_linuxb;
    private javax.swing.JLabel lab_windows;
    // End of variables declaration//GEN-END:variables
}
